<?php
/**
 * Created by PhpStorm.
 * User: svd
 * Date: 14.02.19
 * Time: 14:17
 */
namespace api\components;

use Yii;
use yii\helpers\VarDumper;

class ActiveController extends \yii\rest\ActiveController
{
    /**
     * @param \yii\base\Action $action
     * @return bool
     */
    public function beforeAction($action)
    {
        Yii::info('Received a request for `' . $action->id . '`, HTTP method: ' . Yii::$app->request->method);
        Yii::info('Query params: ' . VarDumper::dumpAsString(Yii::$app->request->getQueryParams()));
        Yii::info('Query string: ' . VarDumper::dumpAsString(Yii::$app->request->getQueryParams()));
        Yii::info('Headers: ' . VarDumper::dumpAsString(Yii::$app->request->getHeaders()));
        Yii::info('Post: ' . VarDumper::dumpAsString(Yii::$app->request->post()));
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}