<?php
/**
 * Created by PhpStorm.
 * User: svd
 * Date: 13.02.19
 * Time: 15:52
 */
namespace common\tests\unit;

use common\helpers\Common;

/**
 * Login form test
 */
class CommonTest extends \Codeception\Test\Unit
{
    /**
     * @var \common\tests\UnitTester
     */
    protected $tester;

    private $allValues = [
        1 => 'v1',
        2 => 'v2',
        4 => 'v3',
        8 => 'v4',
        16 => 'v5',
        32 => 'v6',
        64 => 'v7'
    ];

    private $values = [1, 2, 32];

    private $bitSum = 35;

    /**
     * @var Common $common
     */
    private $common;

    protected function _before()
    {
        $this->common = new Common();
        parent::_before(); // TODO: Change the autogenerated stub
    }

    public function testGetBitSum()
    {
        $this->tester->assertEquals(35, $this->common->getBitSum($this->values));
    }

    public function testGetIntersection()
    {
        $this->tester->assertEquals([
            1 => 'v1', 2 => 'v2', 32 => 'v6'
        ], $this->common->getIntersection($this->allValues, $this->bitSum));
    }
}